# ---------------------------------------------------------------------------
# Excludes
#
# Policy:
#   Exclude only files/directories that can be reproduced from source files,
#   dependency definitions, or build processes.
#
#   Do NOT exclude things merely because they are commonly listed in
#   .gitignore. For example, .env may contain non-reproducible information
#   and therefore should be backed up.
#
# Syntax:
#   "name/"   matches a directory basename.
#   "name"    matches a file basename.
#   Glob metacharacters (*, ?, [...]) are supported.
#
# Examples:
#   "node_modules/"  excludes directories named "node_modules".
#   "*.pyc"          excludes files ending in ".pyc".
#   "CMakeCache.txt" excludes files named "CMakeCache.txt".
#
# Patterns are matched against basenames, not full relative paths.
# ---------------------------------------------------------------------------


EXCLUDED_PATTERNS = {
    # -----------------------------------------------------------------------
    # Version control
    # -----------------------------------------------------------------------
    # Keep repository metadata by default. It may contain local-only commits,
    # branches, tags, stashes, configuration, hooks, and other state that
    # cannot be reproduced from the working tree.
    #
    # ".git/",
    # ".hg/",
    # ".svn/",

    # -----------------------------------------------------------------------
    # Common / editors / OS
    # -----------------------------------------------------------------------

    # Caches are often reproducible, but ".cache" is generic and applications
    # may store valuable state there.
    # ".cache/",

    # Editor configuration is intentionally preserved.
    # ".vscode/",
    # ".idea/",

    # OS metadata is usually disposable, but keeping it is safer for a backup.
    # ".DS_Store",
    # "Thumbs.db",

    # These names are too generic to exclude globally. They are frequently
    # used for generated output, but may also contain source or other
    # non-reproducible data.
    # "bin/",
    # "build/",
    # "dist/",
    # "out/",
    # "output/",
    # "tmp/",
    # "temp/",
    # "cache/",
    # "generated/",
    # "vendor/",

    # -----------------------------------------------------------------------
    # C / C++
    # -----------------------------------------------------------------------

    # CMake in-source/generated metadata.
    "CMakeFiles/",
    "CMakeCache.txt",
    "cmake_install.cmake",
    "CTestTestfile.cmake",

    # CMake-generated files. These are reproducible, but the names are generic
    # enough that hand-written files with the same names are possible.
    # "Makefile",
    # "compile_commands.json",

    # CMake/Ninja build directories are commonly named "build", "cmake-build-*",
    # or "out". Only the tool-specific name is reasonably safe by default.
    "cmake-build-*/",
    # "build/",
    # "out/",

    # Ninja.
    ".ninja_deps",
    ".ninja_log",
    # "build.ninja",  # Usually generated by CMake/Meson, but can be hand-written.

    # Meson.
    "meson-private/",
    "meson-logs/",
    "meson-info/",
    # "meson-out/",
    # "build/",

    # Autotools.
    "autom4te.cache/",
    # "configure",       # Often generated, but commonly distributed as source.
    # "aclocal.m4",      # Same reason.
    # "config.h",
    # "config.log",
    # "config.status",

    # Compiler-generated dependency/object files. These extensions are
    # normally build artifacts, but globally excluding them can theoretically
    # hide intentionally stored binary/object data.
    # "*.o",
    # "*.obj",
    # "*.a",
    # "*.so",
    # "*.dylib",
    # "*.dll",
    # "*.exe",
    # "*.d",

    # clang tooling caches / profiling output.
    ".clangd/",
    # "*.profraw",
    # "*.profdata",

    # Keep configuration.
    # ".clang-format"
    # ".clang-tidy"

    # -----------------------------------------------------------------------
    # Rust / Cargo
    # -----------------------------------------------------------------------

    # Cargo's default build directory. "target" is also a fairly generic name,
    # so preserve it by default in a conservative backup policy.
    # "target/",

    # Cargo configuration and lockfiles are intentionally preserved.
    # "Cargo.lock",
    # ".cargo/",

    # rustfmt/clippy configuration is intentionally preserved.
    # "rustfmt.toml",
    # ".rustfmt.toml",
    # "clippy.toml",

    # -----------------------------------------------------------------------
    # JavaScript / TypeScript / Node.js
    # -----------------------------------------------------------------------

    "node_modules/",

    # Framework/build caches and generated framework state.
    ".next/",
    ".nuxt/",
    ".svelte-kit/",
    ".astro/",
    ".turbo/",
    ".parcel-cache/",

    # Tool caches.
    ".eslintcache",

    # Package manager caches/install state that can be reconstructed.
    ".yarn/cache/",
    ".yarn/unplugged/",
    ".yarn/build-state.yml",
    ".yarn/install-state.gz",

    # pnpm's project-local virtual store.
    "node_modules/.pnpm/",  # Redundant with node_modules/, kept for clarity.

    # Common build output names are intentionally preserved because they are
    # too generic.
    # "dist/",
    # "build/",
    # "out/",

    # TypeScript incremental build information.
    "*.tsbuildinfo",

    # Test/coverage output is reproducible from source + tests, but may be
    # useful historical state and directory names can be generic.
    # "coverage/",

    # Environment files MUST be preserved. They may contain secrets or
    # deployment configuration that cannot be reproduced.
    # ".env",
    # ".env.*",

    # Package-manager lockfiles MUST be preserved.
    # "package-lock.json",
    # "pnpm-lock.yaml",
    # "yarn.lock",
    # "bun.lock",
    # "bun.lockb",

    # -----------------------------------------------------------------------
    # Cloudflare Workers
    # -----------------------------------------------------------------------

    # Local runtime/emulator state may contain non-reproducible data
    # (KV/D1/R2/etc.), so preserve it.
    # ".wrangler/",

    # Wrangler configuration is source/configuration.
    # "wrangler.toml",
    # "wrangler.json",
    # "wrangler.jsonc",

    # -----------------------------------------------------------------------
    # Python / uv
    # -----------------------------------------------------------------------

    "__pycache__/",
    "*.pyc",
    "*.pyo",

    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".pytype/",
    ".hypothesis/",

    # Virtual environments are reproducible only when the project's complete
    # dependency/environment definition is available. They can also contain
    # manually installed packages, so preserve them under a strict backup
    # policy.
    # ".venv/",
    # "venv/",
    # "env/",

    # uv's cache is reproducible, but normally lives outside the project.
    # ".uv-cache/",

    # Python packaging output uses generic directory names.
    # "build/",
    # "dist/",

    # Egg metadata is generated by packaging tools.
    "*.egg-info/",
    ".eggs/",

    # Coverage/test results are reproducible but may represent useful
    # historical state.
    # ".coverage",
    # ".coverage.*",
    # "htmlcov/",
    # "coverage.xml",

    # Dependency definitions and lockfiles MUST be preserved.
    # "pyproject.toml",
    # "uv.lock",
    # "requirements*.txt",

    # -----------------------------------------------------------------------
    # LaTeX
    # -----------------------------------------------------------------------

    # Common auxiliary files generated during compilation.
    "*.aux",
    "*.bcf",
    "*.blg",
    "*.fdb_latexmk",
    "*.fls",
    "*.run.xml",
    "*.synctex.gz",
    "*.toc",

    # minted cache/output.
    "_minted*/",

    # These can be generated but may also be intentionally maintained or
    # useful output, so preserve them conservatively.
    # "*.bbl",
    # "*.ind",
    # "*.gls",

    # Generic extensions with a significant chance of being meaningful files.
    # "*.log",
    # "*.out",

    # Final documents are outputs, but may be expensive/impossible to
    # reproduce exactly (toolchain/fonts/date/external resources/etc.).
    # "*.pdf",

    # -----------------------------------------------------------------------
    # Typst
    # -----------------------------------------------------------------------

    # Typst generally does not create large project-local intermediate build
    # trees. Keep final output by default because exact reproducibility may
    # depend on fonts, Typst version, packages, external resources, etc.
    # "*.pdf",
    # "*.svg",
    # "*.png",

    # -----------------------------------------------------------------------
    # Java / Kotlin
    # -----------------------------------------------------------------------

    # Maven.
    # "target/",  # Generic name; normally safe for Maven, unsafe globally.

    # Gradle.
    ".gradle/",
    # "build/",   # Generic.

    # IDE/project metadata is configuration/state rather than build output.
    # ".idea/",

    # -----------------------------------------------------------------------
    # Go
    # -----------------------------------------------------------------------

    # Go normally keeps caches outside the source tree. Do not globally
    # exclude "bin" or "vendor": both names may contain valuable data.
    # "bin/",
    # "vendor/",

    # go.sum/go.mod are essential reproducibility inputs.
    # "go.mod",
    # "go.sum",

    # -----------------------------------------------------------------------
    # .NET / C#
    # -----------------------------------------------------------------------

    # These are conventional build directories, but their names are generic
    # enough to preserve under a conservative global policy.
    # "bin/",
    # "obj/",

    # -----------------------------------------------------------------------
    # Ruby
    # -----------------------------------------------------------------------

    # Bundler-installed dependencies can be large and reproducible, but
    # "vendor" is too generic for basename-only global exclusion.
    # "vendor/",

    # -----------------------------------------------------------------------
    # PHP / Composer
    # -----------------------------------------------------------------------

    # Composer dependencies are normally reproducible from composer.lock,
    # but "vendor" is too generic for basename-only global exclusion.
    # "vendor/",

    # -----------------------------------------------------------------------
    # Generated archives / backup outputs
    # -----------------------------------------------------------------------

    # Never exclude archives globally. They may themselves be important
    # source assets, releases, datasets, or previous backups.
    # "*.zip",
    # "*.tar",
    # "*.tar.gz",
    # "*.tgz",
    # "*.7z",

    # -----------------------------------------------------------------------
    # Databases / application state
    # -----------------------------------------------------------------------

    # Never exclude databases merely because they are commonly generated.
    # They are frequently the most important non-reproducible data.
    # "*.db",
    # "*.sqlite",
    # "*.sqlite3",

    # -----------------------------------------------------------------------
    # Secrets / credentials / local configuration
    # -----------------------------------------------------------------------

    # These are often ignored by VCS precisely because they contain local,
    # secret, or machine-specific information. That makes them MORE important
    # to a backup, not less.
    # ".env",
    # ".env.*",
    # "*.pem",
    # "*.key",
    # "*.p12",
    # "*.pfx",
}
